# Generated by Django 6.0.6 on 2026-06-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficlog',
            name='ip_address',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trafficlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
