# Generated by Django 6.0.6 on 2026-07-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_alter_trafficlog_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficlog',
            name='request_method',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name='trafficlog',
            index=models.Index(fields=['ip_address', 'timestamp'], name='idx_traffic_ip_ts'),
        ),
    ]
