# Generated by Django 6.0.6 on 2026-08-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0003_alter_trafficlog_request_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficlog',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
