# Generated by Django 6.0.6 on 2026-06-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_systemsettings_ipblocklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100)),
                ('request_count', models.IntegerField()),
                ('threshold', models.IntegerField()),
                ('window_minutes', models.IntegerField()),
                ('path', models.CharField(max_length=255)),
                ('request_method', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='rate_limit_threshold',
            field=models.IntegerField(default=30, help_text='Requests per minute allowed before flagging a rate-limit violation'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='rate_limit_window_minutes',
            field=models.IntegerField(default=1, help_text='Time window in minutes to evaluate rate-limit violations'),
        ),
    ]
