# Generated by Django 6.0.6 on 2026-06-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_ratelimitviolation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='detection_type',
            field=models.CharField(choices=[('traffic_spike', 'Traffic Spike'), ('rate_limit', 'Rate Limit Violation'), ('manual', 'Manual')], default='traffic_spike', max_length=20),
        ),
    ]
