# Generated by Django 6.0.6 on 2026-06-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_add_detection_type_to_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='rate_limit_critical_multiplier',
            field=models.FloatField(default=4.0, help_text='Multiplier for rate limit threshold to trigger CRITICAL severity alerts'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='rate_limit_high_multiplier',
            field=models.FloatField(default=2.0, help_text='Multiplier for rate limit threshold to trigger HIGH severity alerts'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='severity_critical_threshold',
            field=models.IntegerField(default=100, help_text='Requests count threshold for CRITICAL severity spike alerts'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='severity_high_threshold',
            field=models.IntegerField(default=50, help_text='Requests count threshold for HIGH severity spike alerts'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='severity_medium_threshold',
            field=models.IntegerField(default=20, help_text='Requests count threshold for MEDIUM severity spike alerts'),
        ),
    ]
