# Generated by Django 6.0.6 on 2026-06-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_systemsettings_rate_limit_critical_multiplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='auto_block_threshold',
            field=models.IntegerField(default=100, help_text='Request threshold to trigger automatic IP blocking'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_auto_blocking',
            field=models.BooleanField(default=False, help_text='Enable automatic IP blocking when threshold is exceeded'),
        ),
    ]
