# Generated by Django 6.0.6 on 2026-06-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_systemsettings_auto_block_threshold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('req_per_min', models.IntegerField(default=0)),
                ('threshold', models.IntegerField(default=5)),
                ('health', models.CharField(default='normal', max_length=50)),
                ('top_ips_json', models.TextField(default='[]')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
