# Generated by Django 6.0.6 on 2026-06-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0008_monitoringsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='ip_address',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='alert',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='ratelimitviolation',
            name='ip_address',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ratelimitviolation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
