# Generated by Django 6.0.6 on 2026-06-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_alter_alert_ip_address_alter_alert_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_type', models.CharField(choices=[('normal', 'Normal Traffic'), ('spike', 'Traffic Spike'), ('rate_limit', 'Rate-Limit Violation'), ('ddos', 'DDoS Simulation')], max_length=20)),
                ('target_endpoint', models.CharField(default='/', max_length=255)),
                ('num_requests', models.IntegerField(default=100)),
                ('delay_ms', models.IntegerField(default=100)),
                ('simulated_ips_count', models.IntegerField(default=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('stopped', 'Stopped'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('requests_sent', models.IntegerField(default=0)),
                ('requests_blocked', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
