# Generated by Django 6.0.6 on 2026-07-08 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0012_alert_resolved_at_alert_resolved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(db_index=True, max_length=100)),
                ('event_type', models.CharField(choices=[('failed_login', 'Failed Login'), ('lockout', 'Account Lockout'), ('otp_verification', 'OTP Verification'), ('successful_login', 'Successful Login'), ('logout', 'Successful Logout'), ('blocked', 'IP Blocked'), ('whitelist', 'IP Whitelists')], db_index=True, max_length=50)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('details', models.TextField(blank=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(default='shopsafe', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterField(
            model_name='alert',
            name='detection_type',
            field=models.CharField(choices=[('traffic_spike', 'Traffic Spike'), ('rate_limit', 'Rate Limit Violation'), ('brute_force', 'Brute Force Attack'), ('failed_login', 'Failed Login Spike'), ('manual', 'Manual')], default='traffic_spike', max_length=20),
        ),
    ]
