# Generated by Django 6.0.6 on 2026-08-16 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0013_securityevent_alter_alert_detection_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('resolve_alert', 'Resolved Alert'), ('reopen_alert', 'Reopened Alert'), ('block_ip', 'Blocked IP'), ('unblock_ip', 'Unblocked IP'), ('block_device', 'Blocked Device'), ('unblock_device', 'Unblocked Device'), ('whitelist_ip', 'Whitelisted IP'), ('remove_whitelist', 'Removed Whitelist'), ('update_settings', 'Updated Settings'), ('bulk_resolve', 'Bulk Resolved Alerts'), ('change_password', 'Changed Password')], max_length=50),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('failed_login', 'Failed Login'), ('lockout', 'Account Lockout'), ('otp_verification', 'OTP Verification'), ('successful_login', 'Successful Login'), ('logout', 'Successful Logout'), ('blocked', 'IP Blocked'), ('whitelist', 'IP Whitelists'), ('performance_telemetry', 'Performance Telemetry')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='DeviceBlocklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='The User-Agent string or substring to block.', max_length=500)),
                ('match_type', models.CharField(choices=[('contains', 'Contains'), ('exact', 'Exact Match')], default='contains', help_text='How to match the identifier against incoming User-Agent headers.', max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
    ]
